import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "./components/Header";
import SessionProviderWrapper from "@/components/providers/session-provider"; // インポート
import { auth } from "@/lib/auth"; // インポート

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth(); // セッション情報を取得

  return (
    <html lang="ja">
      <body className={inter.className}>
        <SessionProviderWrapper session={session}> {/* SessionProviderWrapperでラップ */}
          <Header />
          {children}
        </SessionProviderWrapper>
      </body>
    </html>
  );
}

